### ISSUE TITLE
dt too high (n)ms. Capped to 500ms

### ISSUE THREAD

**Issue by RichardBosworth** [kefniark/Fatina#49]
Hi,

I'm having trouble with the initial tweening operation. I am trying to smooth an SVG viewbox zoom animation that uses the mousewheel. The initial tweening fails with the above warning. The latter ones work as expected.

How can I fix this issue?

Thanks,
Richard

**Comment by RichardBosworth** [comment]
`fromEvent(window, 'wheel').subscribe((value: WheelEvent) => {
      const currentViewBox = this.svg.workingDocument.viewbox();

      let moveDelta = value.deltaY * 3;

      Fatina.tween(currentViewBox)
        .to({
          width: currentViewBox.width + (moveDelta),
          height: currentViewBox.height + (moveDelta)
        }, 1000)
        .setEasing(EasingType.InOutExponential)
        .onUpdate((dt) => console.log(dt))
        .start();

      this.svg.workingDocument.viewbox({
        x: currentViewBox.x,
        y: currentViewBox.y,
        width: currentViewBox.width + value.deltaY,
        height: currentViewBox.height + value.deltaY
      });
    });`

**Comment by kefniark** [comment]
> The initial tweening fails

What is failing exactly? is there any error or the animation is just not smooth enough?
This warning is just here to let us know that the update loop is skipping many frames (500ms is like more than 30frames) and the library cannot keep smooth animation.

I realize this happen more often recently (probably related to browser updates in path months), the first `requestAnimationFrame` deltatime seems to also contain the delay between the **DOMContentLoaded** and **OnLoad** events which can on page with lot of css/js can take quite some time ~1s

I noticed a similar issue while working on the `3.0` (not smooth first frame) and I fixed it by just skipping this frame. If you confirm me it's the same issue, I can backport the fix (skipping this frame if the deltatime is too high).
https://github.com/kefniark/Fatina/pull/48/files#diff-5a1ea26a25fdc7dc16e789ed57ad9518R401

**Comment by kefniark** [comment]
Not related to your issue, 
But for your code I recommend killing previous tweens when you start a new one on the same object.
This avoid trouble and is more efficient ^^

```js
let animTween;

fromEvent(window, 'wheel').subscribe((value: WheelEvent) => {
    if (animTween) animTween.kill();
    animTween = Fatina.tween(currentViewBox).start();
});
```

**Comment by kefniark** [comment]
no feedback about ```If you confirm me it's the same issue, I can backport the fix``` ?

**Comment by kefniark** [comment]
So no news about this issue, and last time I've seen something close to that it was related to the page onLoad event and not fatina.
Anyway, can't reproduce it with last develop.
