### ISSUE TITLE
Require / Import Syntax

### ISSUE THREAD

**Issue by kefniark** [kefniark/Fatina#53]
## Description

With the new version of [Fatina v3.0](https://github.com/kefniark/Fatina/releases/tag/v3.0.0), the syntax of import slightly changed:

**Typescript** / **ESM modules**
```js
import * as Fatina from 'fatina';
// become
import Fatina from 'fatina';
```

**CommonJS (Node)**
```js
var Fatina = require('fatina');
// become
var Fatina = require('fatina').default;
```

**Web / CDN**
Nothing change, still use global variable **Fatina**

## Why ?
Sorry for the modification, this default export really makes auto-completion and declaration support easier to manage.

![image](https://user-images.githubusercontent.com/4903529/66144561-08b8bc80-e644-11e9-95dc-7f61d4082715.png)
![image](https://user-images.githubusercontent.com/4903529/66144744-5c2b0a80-e644-11e9-8a68-5625653224f0.png)

**Comment by kebab-banana** [comment]
thanks, I was about to open issue related to vscode auto-completion 😄
