### ISSUE TITLE
uglyfy gives an error

### ISSUE THREAD

**Issue by indikaUih** [kefniark/Fatina#55]
when trying to uglify the .js file it throws an error in Fatina code. 

ct";Object.defineProperty(e,"__esModule",{value:!0});e.BaseTween=class{construct

ERROR: Unexpected token: punc «{», expected: punc «;»

Minify works but thought you might be able to help out here.

**Comment by kefniark** [comment]
hum can you give me more info about your environment?

I'm using this lib quite regularly and I never seen such error 😄

**Comment by kefniark** [comment]
Ha ... now I think about it, fatina is writen in ES6 and if I remember the original Minifyjs is quite outdated and still ES5 and require transpiling tools like babel

If you can change, there are better alternative nowadays like [Terser](https://github.com/terser/terser)

```
```

**Comment by indikaUih** [comment]
Hi Kevin,

I could change and it worked like a charm :)

Thanks very much.
Indika Herath

**Comment by kefniark** [comment]
I'm glad it helped you 👏

Have a nice day
