### ISSUE TITLE
How to manually tick Fatina?

### ISSUE THREAD

**Issue by smjnab** [kefniark/Fatina#83]
Hey!

I can't figure out how to manually tick Fatina from my own update loop. I can see in the docs that it is meant to work "If you already have an update loop, try to tick manually Fatina to keep animation and rendering in sync", but can't get it to work.

I thought Fatina.pause() and then Fatina.update(timestamp) in the loop should do it, but the test tween will not tick (works fine if I let Fatina do it on its own).

Thank you!

**Comment by kefniark** [comment]
Ha indeed, Sorry I feel like I had a paragraph in the doc about that at some point, but I can't find it.

Fatina by default automatically update itself, if you want to disable this behavior, it's a one liner.
When you start your app, you just have to tell fatina to not auto update with requestAnimationFrame
```ts
// public init(disableAutoTick?: boolean): boolean
Fatina.init(true)
```

Then you can update it yourself with ```Fatina.update(dt)``` in your update loop

---

To illustrate this:
* here is a normal fatina usage https://codepen.io/kefniark/pen/podzpLY
* the same with manual update https://codepen.io/kefniark/pen/xxjXrgW

**Comment by smjnab** [comment]
Ah, perfect. Thank you, working nicely now :)

It was mentioned under more -> tips
